services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  loader:
    build: .
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      DB_NAME: mydb
      COLLECTION_NAME: mycollection
      CSV_PATH: /app/data/healthcare_dataset.csv
    volumes:
      - ./data:/app/data
    command: python migration.py

volumes:
  mongo_data: