services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  loader:
    build: .
    depends_on:
      - mongo
    volumes:
      - ./data:/app/data
    command: python migration.py

  auth_app:
    build: .
    depends_on:
      - mongo
    stdin_open: true   
    tty: true         
    command: python auth_app.py

volumes:
  mongo_data:
